-- MySQL Script generated by MySQL Workbench
-- Wed Jun  9 17:49:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema insumo_tecnologico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insumo_tecnologico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insumo_tecnologico` DEFAULT CHARACTER SET utf8 ;
USE `insumo_tecnologico` ;

-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Rol` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Administrador_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idAdministrador`),
  CONSTRAINT `fk_Administrador_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `insumo_tecnologico`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `insumo_tecnologico`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `fk_Compras_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `insumo_tecnologico`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Insumos` (
  `idInsumos` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NOT NULL,
  `Cantidad` TINYINT(1) NOT NULL,
  `Imagen` MEDIUMBLOB NOT NULL,
  `Precio` DECIMAL(8,2) NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `Compras_idCompras` INT NOT NULL,
  PRIMARY KEY (`idInsumos`),
  INDEX `fk_Insumos_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  INDEX `fk_Insumos_Compras1_idx` (`Compras_idCompras` ASC) VISIBLE,
  CONSTRAINT `fk_Insumos_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `insumo_tecnologico`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_Compras1`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `insumo_tecnologico`.`Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_Proveedor_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `insumo_tecnologico`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insumo_tecnologico`.`InsumosSinIVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumo_tecnologico`.`InsumosSinIVA` (
  `idInsumosSinIVA` INT NOT NULL AUTO_INCREMENT,
  `Detalle` VARCHAR(45) NOT NULL,
  `Cantidad` TINYINT(1) NOT NULL,
  `Precio` DECIMAL(8,2) NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idInsumosSinIVA`),
  INDEX `fk_InsumosSinIVA_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_InsumosSinIVA_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `insumo_tecnologico`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
